SELECT
  C.ID,
  C.LASTNAME,
  C.FIRSTNAME,
  SUM(P.PRICE)
FROM CUSTOMERS C
  JOIN ORDERS O ON C.ID = O.CUSTOMER_ID
  JOIN ORDERITEMS I ON O.ID = I.ORDER_ID
  JOIN PRODUCTS P ON I.PRODUCT_ID = P.ID
WHERE LOWER(C.LASTNAME) LIKE LOWER(?)
GROUP BY C.ID, C.LASTNAME, C.FIRSTNAME
ORDER BY C.LASTNAME, C.FIRSTNAME